version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  go:test:
    cmds:
      - go test github.com/ecshreve/slomad/...

  go:test:verbose:
    cmds:
      - go test -v github.com/ecshreve/slomad/...

  go:test:cov:
    cmds:
      - go test -race -coverprofile=cover.out -covermode=atomic github.com/ecshreve/slomad/...
      - go tool cover -html cover.out -o cover.html

  go:build:
    generates:
      - bin/slomad
    sources:
      - ./**/*.go
      - ./**/config/*.yml
    cmds:
      - go build -o bin/slomad github.com/ecshreve/slomad/cmd/slomad

  go:run:
    deps:
      - go:build
    cmds:
      - bin/slomad {{.CLI_ARGS}}