version: "3"
  
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    cmds:
      - task --list-all

  go:test:
    cmds:
      - go test github.com/ecshreve/slomad/...

  go:test:verbose:
    cmds:
      - go test -v github.com/ecshreve/slomad/...

  go:test:cover:
    cmds:
      - go test -race -coverprofile=reports/cover.out -covermode=atomic github.com/ecshreve/slomad/...
  
  go:test:cover:serve:
    deps:
      - go:test:cover
    cmds:
      - go tool cover -html reports/cover.out -o reports/cover.html
      - cd reports && python3 -m http.server 8008

  go:build:
    generates:
      - bin/slomad
    sources:
      - ./**/*.go
      - ./**/config/*.yml
      - ./**/config/**/*.yml
    cmds:
      - go build -o bin/slomad github.com/ecshreve/slomad/cmd/slomad

  go:doc:serve:
    cmds:
      - godoc -http=:6060

  go:doc:gen:
    cmds:
      - gomarkdoc -u ./...
    sources:
      - ./**/*.go
      - ./**/config/*.yml
    generates:
      - ./**/*.md

  go:run:
    deps:
      - go:build
    cmds:
      - bin/slomad {{.CLI_ARGS}}