---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: "synology-exporter"
    static_configs:
      - targets: ["10.35.90.50:9100", "10.35.90.40:9100"]

  - job_name: "docker-coderbox"
    static_configs:
      - targets: ["10.35.220.99:9323"]

  - job_name: "nomad-metrics"
    consul_sd_configs:
      - server: <CONSUL_TARGET>
        datacenter: "dcs"
        services: ["nomad-client", "nomad"]
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        separator: ;
        regex: (.*)http(.*)
        replacement: $1
        action: keep
      - source_labels: [__meta_consul_address]
        regex: (.*)
        target_label: __meta_consul_service_address
        replacement: $1
        action: replace
      - source_labels: [__meta_consul_node]
        regex: (.*)
        target_label: node
        replacement: $1
        action: replace
    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ["prometheus"]

  - job_name: "consul-metrics"
    consul_sd_configs:
      - server: <CONSUL_TARGET>
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    scheme: "http"
    relabel_configs:
      - source_labels: ["__address__"]
        regex: "(.*):(.*)"
        replacement: "$1:8500"
        action: replace
        target_label: "__address__"

  - job_name: "node-exporter"
    consul_sd_configs:
      - server: <CONSUL_TARGET>
        datacenter: "dcs"
        scheme: "http"
        services: ["node-exporter"]
    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex:         '(.*)'
        target_label:  'job'
        replacement:   '$1'
      - source_labels: ['__meta_consul_node']
        regex:         '(.*)'
        target_label:  'instance'
        replacement:   '$1'
