---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nomad_metrics"
    consul_sd_configs:
      - server: "10.35.220.50:8500"
        datacenter: "dcs"
        services: ["nomad-client", "nomad"]
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        separator: ;
        regex: (.*)http(.*)
        replacement: $1
        action: keep
      - source_labels: [__meta_consul_address]
        regex: (.*)
        target_label: __meta_consul_service_address
        replacement: $1
        action: replace
    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ["prometheus"]

  - job_name: "consul_metrics"
    consul_sd_configs:
      - server: "10.35.220.50:8500"
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]
    scheme: "http"
    relabel_configs:
      - source_labels: ["__address__"]
        regex: "(.*):(.*)"
        replacement: "$1:8500"
        action: replace
        target_label: "__address__"

  - job_name: "nodeexp"
    consul_sd_configs:
      - server: "10.35.220.50:8500"
        datacenter: "dcs"
        scheme: "http"
        services: ["nodeexporter"]
    relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex:         '(.*)'
        target_label:  'job'
        replacement:   '$1'
      - source_labels: ['__meta_consul_node']
        regex:         '(.*)'
        target_label:  'instance'
        replacement:   '$1'
